---
- name: dotfiles | include passwords
  include_vars:
    file: passwords.yml

- name: dotfiles | install packages
  pacman:
    name:
      - neovim
      - git
      - tmux
      - neomutt
      - notmuch
      - offlineimap
      - vdirsyncer
      - zsh
      - zsh-completions
      - youtube-dl
      - khard
      - khal
      - todoman
      - ripgrep
      - msmtp
      - openssh
      - pass
    state: latest
  become: yes
  tags:
    - packages

- name: dotfiles | create config directories
  file: path={{ item }} state=directory
  loop:
    - ~/.config
    - ~/.config/gnupg
    - ~/.config/neomutt
    - ~/.config/neomutt/accounts
    - ~/.config/nvim
    - ~/.config/khal
    - ~/.config/khard
    - ~/.config/systemd
    - ~/.config/systemd/user
    - ~/.config/todoman
    - ~/.config/vdirsyncer
    - ~/.config/youtube-dl
    - ~/.gnupg
    - ~/.local
    - ~/.local/bin
    - ~/.ssh
    - ~/.zsh

- name: dotfiles | create symlinks
  file: src={{ ansible_env.PWD }}/roles/dotfiles/files/{{ item }}
        path=~/{{ item }}
        state=link
        force=yes
  loop: '{{dotfiles_files}}'

- name: dotfiles | create templates
  template: dest={{ ansible_env.HOME }}/{{ item }}
            mode={{ '0755' if item.endswith('.sh') else '0600' }}
            src={{ item }}
  loop: '{{templates_files}}'

- name: dotfiles | enable user services
  systemd:
    name: '{{ item }}'
    daemon_reload: yes
    scope: user
    enabled: yes
    state: started
  loop: '{{services}}'
