#!/bin/zsh
##################
# zsh config file
##################

# history
export HISTSIZE=2000
export HISTFILE="$HOME/.history"
export SAVEHIST=$HISTSIZE

# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored _correct _approximate
zstyle ':completion:*' list-colors ''
zstyle :compinstall filename '/home/justin/.zshrc'

autoload -Uz compinit
compinit

setopt correctall

autoload -U promptinit
promptinit

autoload -U colors && colors
#prompt suse

PROMPT="%{$fg[green]%}%n%{$reset_color%}@%{$fg[blue]%}%m %{$fg[yellow]%}%1~ %{$reset_color%}%# "

# alias
alias grep='grep --color=auto'

## Set zsh to the vi mod
set -o vi

## Set the default editor
export EDITOR=/usr/bin/vim

## Set the default pager
export PAGER=/usr/bin/less

## Path for macport package
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
