---
- name: system | install config
  file: src={{ ansible_env.PWD }}/roles/system/files/{{ item }}
        path=/etc/{{ item }}
        state=link
        force=yes
  loop:
    - pacman.conf
    - makepkg.conf
  become: yes

- name: system | update system package list
  pacman:
    update_cache: yes
  become: yes
  tags:
    - packages

- name: system | install general package
  pacman:
    name:
      - dialog
      - mosh
      - netctl
      - openssh
      - openvpn
      - unzip
      - wpa_supplicant
    state: latest
  become: yes
  tags:
    - packages

- name: system | install paru
  aur:
    name: paru
  tags:
    - packages

- name: system | install openvpn update resolv script
  aur:
    name: openvpn-update-resolv-conf-git
  tags:
    - packages
