---
- name: system | install config
  file: src={{ ansible_env.PWD }}/roles/system/files/{{ item }}
        path=/etc/{{ item }}
        state=link
        force=yes
  loop:
    - pacman.conf
    - makepkg.conf
  become: yes

- name: system | install network package
  pacman:
    name:
      - dialog
      - netctl
      - openvpn
      - wpa_supplicant
    state: latest
  become: yes
  tags:
    - packages

- name: system | install yay
  aur:
    name: yay
  tags:
    - packages
