---
- name: wm | install packages
  pacman:
    name:
      - alsa-utils
      - awesome
      - feh
      - fontconfig
      - lightdm
      - lightdm-gtk-greeter
      - light-locker
      - mpv
      - powerline-fonts
      - pulseaudio
      - pulseaudio-alsa
      - pulsemixer
      - rxvt-unicode
      - rxvt-unicode-terminfo
      - shotgun
      - slop
      - ttf-jetbrains-mono
      - vicious
      - xclip
      - xorg-server
      - xorg-xkbcomp
      - xorg-xmodmap
      - xorg-xprop
      - xorg-xrandr
      - xorg-xrdb
    state: latest
  become: yes
  tags:
    - packages

- name: wm | create wm related config directory
  file: path={{ item }} state=directory
  loop:
    - ~/.config
    - ~/.config/awesome
    - ~/.local
    - ~/.local/bin

- name: wm | install wm related config
  file: src={{ role_path }}/files/{{ item }}
        path=~/{{ item }}
        state=link
        force=yes
  loop: '{{ wm_config_files }}'

- name: wm | enable pulseaudio service
  systemd:
    name: pulseaudio.service
    daemon_reload: yes
    scope: user
    enabled: yes
    state: started
