---
- name: wm | install packages
  pacman:
    name:
      - alsa-utils
      - awesome
      - fontconfig
      - lightdm
      - lightdm-gtk-greeter
      - light-locker
      - rxvt-unicode
      - rxvt-unicode-terminfo
      - shotgun
      - slop
      - vicious
      - xclip
      - xorg-server
      - xorg-xkbcomp
      - xorg-xmodmap
      - xorg-xprop
      - xorg-xrandr
      - xorg-xrdb
    state: latest
  become: yes
  tags:
    - packages

- name: wm | install patched fonts
  aur:
    name:
      - ttf-dejavu-sans-mono-powerline
      - urxvt-tabbedex
  tags:
    - packages

- name: wm | create wm related config directory
  file: path={{ item }} state=directory
  loop:
    - ~/.config
    - ~/.config/awesome
    - ~/.local
    - ~/.local/bin

- name: wm | install wm related config
  file: src={{ ansible_env.PWD }}/roles/wm/files/{{ item }}
        path=~/{{ item }}
        state=link
        force=yes
  loop: '{{ wm_config_files }}'
