---
- name: awesome | install packages
  pacman:
    name:
      - awesome
      - fontconfig
      - rxvt-unicode
      - rxvt-unicode-terminfo
      - shotgun
      - slop
      - vicious
      - xclip
      - xorg-server
      - xorg-xkbcomp
      - xorg-xmodmap
      - xorg-xprop
      - xorg-xrandr
      - xorg-xrdb
    state: latest
  become: yes
  tags:
    - packages

- name: awesome | create awesome config directory
  file: path={{ item }} state=directory
  loop:
    - ~/.config
    - ~/.config/awesome

- name: awesome | install mpd config
  file: src={{ ansible_env.PWD }}/roles/awesome/files/{{ item }}
        path=~/{{ item }}
        state=link
        force=yes
  loop: '{{ awesome_config_files }}'
