---
- name: mpd | install packages
  pacman:
    name:
      - mpd
      - ncmpcpp
      - playerctl
    state: latest
  become: yes

- name: mpd | install mpd-mpris
  aur:
    name: mpd-mpris

- name: mpd | create mpd config directories
  file: path={{ item }} state=directory
  loop:
    - ~/.config/mpd
    - ~/.config/mpd/playlists
    - ~/.ncmpcpp

- name: mpd | install mpd config
  file: src={{ ansible_env.PWD }}/roles/mpd/files/{{ item }}
        path=~/{{ item }}
        state=link
        force=yes
  loop:
    - .config/mpd/mpd.conf
    - .ncmpcpp/config
