---
- name: mpd | install packages
  pacman:
    name:
      - mpd
      - mpc
      - ncmpcpp
      - playerctl
    state: latest
  become: yes
  tags:
    - packages

- name: mpd | install mpd-mpris
  aur:
    name: mpd-mpris
  tags:
    - packages

- name: mpd | delete old ncmpcpp config directory
  file: path=~/.ncmpcpp state=absent

- name: mpd | create mpd config directories
  file: path={{ item }} state=directory
  loop:
    - ~/.config/mpd
    - ~/.config/mpd/playlists
    - ~/.config/ncmpcpp

- name: mpd | install mpd config
  file: src={{ role_path }}/files/{{ item }}
        path=~/{{ item }}
        state=link
        force=yes
  loop:
    - .config/mpd/mpd.conf
    - .config/ncmpcpp/config
    - .config/ncmpcpp/bindings

- name: mpd | enable services
  systemd:
    name: '{{ item }}'
    daemon_reload: yes
    scope: user
    enabled: yes
    state: started
  loop:
    - mpd
    - mpd-mpris
