---
- name: apps | install browsers
  pacman:
    name:
      - firefox-developer-edition
      - chromium
    state: latest
  become: yes
  tags:
    - packages

- name: apps | install zathura
  pacman:
    name:
      - zathura
      - zathura-djvu
      - zathura-pdf-poppler
      - zathura-ps
    state: latest
  become: yes
  tags:
    - packages
    - chat

- name: apps | install nextcloud client
  pacman:
    name:
      - nextcloud-client
    state: latest
  become: yes
  tags:
    - packages

- name: apps | install signal-desktop
  pacman:
    name:
      - signal-desktop
    state: latest
  become: yes
  tags:
    - packages
    - chat

- name: apps | install mattermost client
  aur:
    name:
      - mattermost-desktop
  tags:
    - packages
    - chat
