---
- name: touchpad | install xorg-xinput
  pacman:
    name: xorg-xinput
    state: latest
  become: yes
  tags:
    - packages

- name: touchpad | install touchpad config
  file: src={{ role_path }}/files/.Xsession
        path=~/.Xsession
        state=link
        force=yes
