---
- name: touchpad | install necessary package
  pacman:
    name: xorg-xinput
    state: latest

- name: touchpad | install touchpad config
  file: src={{ ansible_env.PWD }}/roles/touchpad/files/.Xsession
        path=~/.Xsession
        state=link
        force=yes
