#!/bin/bash

## term server ##
#urxvtd -q -f -o

## transparency ##
xcompmgr -CcFf &

mpd &

feh --bg-center --no-xinerama /home/justin/images/railway.png &
dropboxd &
tint2 &
thunderbird &
firefox&
ario&
skype &
