#!/bin/bash

## term server ##
#urxvtd -q -f -o

## transparency ##
xcompmgr -CcFf &

mpd &

feh --bg-center --no-xinerama /home/justin/images/water.jpg &
dropboxd &
tint2 &
thunderbird &
firefox&
sonata&
skype &
