---
- name: awesome | install packages
  pacman:
    name:
      - awesome
      - vicious
    state: latest

- name: awesome | create awesome config directory
  file: path={{ item }} state=directory
  loop:
    - ~/.config
    - ~/.config/awesome

- name: awesome | install mpd config
  file: src={{ ansible_env.PWD }}/roles/awesome/files/{{ item }}
        path=~/{{ item }}
        state=link
        force=yes
  loop: '{{ awesome_config_files }}'
