- name: nvim | install neovim-git
  aur:
    name:
      - neovim-git
  tags:
    - packages

- name: nvim | symlink config
  file: src={{ role_path }}/files/nvim
        path=~/.config/nvim
        state=link
        force=yes
