- name: nvim | install neovim related packages
  aur:
    name:
      - neovim-git
      - vscode-css-languageserver-bin
  tags:
    - packages

- name: nvim | symlink config
  file: src={{ role_path }}/files/nvim
        path=~/.config/nvim
        state=link
        force=yes
